# Generated by Django 5.0.7 on 2024-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
