# Generated by Django 5.0 on 2024-08-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autho_app', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
